(define (tree r)
 (if (< r 10) (begin (forward r) (backward r))
  (begin (forward (/ r 4))
   (right 30)
   (tree (/ r 2))
   (left 50)
   (tree (/ r 2))
   (right 20)
  (backward (/ r 4)))))

(define (tree-spiral size)
 (tree size)
 (right 45)
 (tree size)
 (right 45)
 (tree size)
 (right 45)
 (tree size)
 (right 45)
 (tree size)
 (right 45)
 (tree size)
 (right 45)
 (tree size)
 (right 45)
 (tree size)
 (right 45))

(define (draw)
 (bgcolor (rgb 0 0 .2))
 (color (rgb .5 .5 0))
 (speed 10)
 (setposition 0 0)
 (tree-spiral 400)
 (exitonclick))

(draw)